server:
  #设置程序启动端口号
  port: 7000
  servlet:
      context-path: /web






spring:
  aop:
  #开启aop代理
    auto: true
    proxy-target-class: true
  datasource:
     driver-class-name: com.ibm.db2.jcc.DB2Driver
     username: sam
     password: 123456
     url: jdbc:db2://192.168.41.151:50000/sam
     type: com.alibaba.druid.pool.DruidDataSource
     druid:
       # 初始连接数
       initial-size: 5
       # 最大激活数
       max-active: 50
       # 最大等待时间
       max-wait: 3000
       # 是否启用非公平锁
       use-unfair-lock: true
       # mysql 用 false | oracle 用 true
       pool-prepared-statements: false
  mvc:
      view:
      #  prefix: /jsp/
        prefix: /
        suffix: .jsp
      pathmatch:
        use-suffix-pattern: false
        use-registered-suffix-pattern: true
      contentnegotiation:
        favor-path-extension: false


nutz:
  json:
    auto-unicode: false
    quote-name: true
    ignore-null: true
    null-as-emtry: true
    enabled: true
    mode: compact
  dao:
    runtime:
      create: false #自动创建表
      migration: false #根据bena自动更新表结构
      basepackage: com.efraiser.test.db.model  #扫描bean
    sqlmanager:
      paths:
        - sqls  #sql文件存放位置

mine:
  properties:
    updateEnabled: false
    loginImg1: images/login/top-39.gif
    loginImg2: url(images/login/bg_main_exam.gif) no-repeat
    mainImg: images/cbrc.png
    dateFormat: 1
    eastScoreShow: 2  #省局east打分展示 1 表示展示
    mainJsp: main
    systemBrNo:
    ef: true
    cacheNameStr:     #模块使用缓存(跟CACHE_INFO表对应) eg：sysBmglCache,sysGgzdCache





